myProject/blogposts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField,SubmitField, TextAreaField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Text', widget=TextArea(), validators=[DataRequired()])
    submit = SubmitField('Post')

myProject/blogposts/views.py
from flask import Blueprint,redirect,render_template,url_for
from myProject import db, mail
from myProject.models import RegisteredMember, BlogPost
from myProject.blogposts.forms import BlogPostForm
from flask import render_template,redirect,request,url_for,flash,abort
from flask_login import login_user, login_required,logout_user, current_user
from flask import Flask


blog_post_bp = Blueprint('blog_post_bp',__name__,
                                template_folder='templates/blogposts')


@blog_post_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(title = form.title.data,
                                text = form.text.data,
                                user_id = current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog post successfully created')
        return redirect(url_for('member_login.profile'))
    return render_template('create_post.html', form=form)

@blog_post_bp.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title = post.title, date = post.date, post = post)
 

@blog_post_bp.route('/<int:blog_post_id>/update', methods = ['GET','POST'])
@login_required
def update(blog_post_id):
    post = BlogPost.query.get_or_404(blog_post_id)
    if post.author != current_user:
        abort(403)
    form = BlogPostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        db.session.commit()
        flash('Blog post successfully updated')
        return redirect(url_for('.blog_post',blog_post_id=blog_post_id))
    elif request.method=='GET':
        form.title.data = post.title
        form.text.data = post.text
    return render_template('create_post.html', title = 'Updating', form=form)


@blog_post_bp.route('/<int:blog_post_id>/delete', methods = ['GET','POST'])
@login_required
def delete(blog_post_id):
    post = BlogPost.query.get_or_404(blog_post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash("Blog Post deleted")
    return redirect(url_for('member_login.profile'))


# @member_profiles_bp.route('/list')
# @login_required
# def list_register_members():
#     members = RegisteredMember.query.all()
#     return render_template("thankyou.html", members=members)


# @member_profiles_bp.route('/thankyou')
# @login_required
# def thankyou():
#     return render_template("thankyou.html")

myProject/blogposts/templates/blogposts/blog_post.html
{% extends "base_dashboard.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>{{ post.title }}</h1>
        <h2>Written By: {{ post.author.username }} </h2>
        <p>
            {{ post.text }}
        </p>
        <div>
            <a href="{{url_for('blog_post_bp.update',blog_post_id=post.id)}}"> Update </a> 
            <button type="button" name="button" class="btn btn-danger" data-toggle="modal" data-target='#del_modal'>Delete</button>
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id='del_modal'>
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete {{post.title}}</p>
            </div>
            <div class="modal-footer">
              <form action="{{url_for('blog_post_bp.delete',blog_post_id=post.id)}}" method="POST">
                <input type="submit" class="btn btn-danger" value="Delete">

              </form>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>
</div>

   


{% endblock %}

myProject/blogposts/templates/blogposts/create_post.html
{% extends "base_dashboard.html" %}
{% block content %}
<div class="container">
    <form method="POST">
        {{ form.hidden_tag() }}
    <div class="form-group">
        <label for="exampleFormControlInput1">Title</label>
        {{ form.title(id='exampleFormControlInput1' ,class_='form-control')}}
        <!-- <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com"> -->
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Text</label>
        {{ form.text(rows="10", id='exampleFormControlTextarea1', class_='col-md-12 form-control-lg')}}
        <!-- <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea> -->
    </div>
    {{ form.submit(class_='btn btn-primary mb-2') }}
    <!-- <button type="submit" class="btn btn-primary mb-2">Confirm identity</button> -->
    </form>
</div>



{% endblock %}

myProject/blogposts/templates/blogposts/user_blogs.html
{% extends "base_dashboard.html" %}
{% block content %}
{% for post in blogposts.items %}
<div class="container col-md-12">
    <div align='center'>        
        <h2><a href="#"> {{post.title}} </a></h2>
        Written By: <a>{{post.author.username}}</a>
        <br>
        <p>
        {{ post.text }}
        </p>
        {% endfor %}

        <!-- Pagination -->

        <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% for page_num in blogposts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)%}
            {% if blogposts.page == page_num %}
                <li class="page-item" disabled>
                    <a class="page-link" href="{{url_for('member_login.users_posts',username = user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('member_login.users_posts',username = user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
            {% endif %}
        {% endfor %}
        </ul>
        </nav>
    </div>
</div>

{% endblock %}