myProject/member_login/views.py
from flask import Blueprint,render_template,redirect,url_for
from myProject import db
from myProject.models import RegisteredMember, BlogPost
from myProject.member_login.forms import LoginForm, SignUpForm, ProfileForm
from flask import render_template,redirect,request,url_for,flash,abort
from flask_login import login_user, login_required,logout_user, current_user
from myProject.member_login.token import genrate_token, confirm_token
from myProject.member_login.email import send_email
from myProject.member_login.decorators import check_confirmed
from myProject.member_login.picture_handler import add_profile_pic
from datetime import datetime


member_login_bp =  Blueprint('member_login',__name__,
                            template_folder='templates/member_login')

'''
Blueprint for signup form
'''
@member_login_bp.route("/signup",methods=['GET','POST'])
def sign_up():
    form = SignUpForm()
    if form.validate_on_submit():
        member = RegisteredMember(fullname=form.fullname.data,
                                    useremail=form.useremail.data,
                                    username=form.username.data,
                                    password=form.password.data,
                                    confirmed=False)
        db.session.add(member)
        db.session.commit()
        token = genrate_token(member.useremail)
        confirm_url = url_for('.confirm_email', token = token, _external= True)
        html = render_template('confirm_url.html', confirm_url = confirm_url) 
        subject = "Confirm your email"
        send_email(member.useremail,subject,html)
        login_user(member)
        flash("Thank you for Registration, A confirmation email has been sent to you!", "success")
        return redirect(url_for('.unconfirmed'))
    return render_template('signup.html',form=form)

'''
Sign in View
'''

@member_login_bp.route("/sign_in",methods=['GET','POST'])
def sign_in():
    form = LoginForm()
    submission = False 
    message = ''

    if form.validate_on_submit():
        useremail = form.useremail.data
        password = form.password.data
        reg = RegisteredMember.query.filter_by(useremail=useremail).first()
        if reg is not None:
            if  reg.check_password(password): 
                login_user(reg)
                submission = True
                message = 'Log In successfull'
                # next = request.args.get('next')
                # if (next == None) or (not next[0] == "/"):
                #     next = url_for('.profile')
                return redirect(url_for('.profile'))
            elif reg.password != password:
                message = 'Incorrect password'
        elif reg is None:
                message = 'Incorrect email id'
    elif request.method == 'GET':
        form.useremail.data = request.args.get('useremail')
        form.password.data = request.args.get('password')
    return render_template("signin.html",form=form , message = message, submission=submission)


'''
confirm_email view

'''
@member_login_bp.route('/confirm/<token>')  
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired','danger')
    user = RegisteredMember.query.filter_by(useremail=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed, please login', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account', 'success')
    return redirect(url_for('.profile'))

'''
Unconfirmed route

'''

@member_login_bp.route('/unconfirmed')

def unconfirmed():
    if current_user.confirmed:
        return redirect(url_for('core.index'))
    flash('Please confirm your account!', 'warning')
    return render_template('unconfirmed.html')


'''
dashboard
'''
@member_login_bp.route('/profile', methods=['GET','POST'])
@login_required
@check_confirmed
def profile():
    page = request.args.get('page',1,type=int)
    blogposts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('dashboard.html',blogposts=blogposts)


'''
Resend email 
'''
@member_login_bp.route('/resend')
@login_required
def resend_confirmation():
    token = genrate_token(current_user.useremail)
    confirm_url = url_for('.confirm_email', token = token, _external = True)
    html = render_template('confirm_url.html', confirm_url= confirm_url)
    subject = 'Please confirm your email'
    send_email(current_user.useremail,subject,html)
    flash('A new confirmation email has been sent to you!', 'success')
    return redirect(url_for('.unconfirmed'))

'''
Profile view
'''


@member_login_bp.route('/user_profile', methods = ['GET','POST'])
def user_profile():
    form = ProfileForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_pic = pic
        current_user.username = form.username.data
        current_user.useremail = form.useremail.data
        current_user.first_name = form.first_name.data
        form.last_name.data= form.last_name.data
        current_user.address = form.address.data
        current_user.city = form.city.data
        current_user.country = form.country.data
        current_user.postal_code = form.postal_code.data
        current_user.about_me = form.about_me.data

        db.session.commit()
        flash('User account updated')
        return redirect(url_for('.uesr_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.useremail.data = current_user.useremail
        form.first_name.data = current_user.first_name
        form.last_name.data = form.last_name.data
        form.address.data = current_user.address
        form.city.data = current_user.city
        form.country.data = current_user.country
        form.postal_code.data = current_user.postal_code
        form.about_me.data = current_user.about_me
    profile_image = url_for('static' , filename = 'profile_pics/'+current_user.profile_pic)
    return render_template('user_profile.html', profile_image = profile_image , form = form)




'''
Blog post
'''

@member_login_bp.route("/<username>")
def users_posts(username):
    page = request.args.get('page',1,type=int)
    user = RegisteredMember.query.filter_by(username=username).first_or_404()
    blogposts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blogs.html',blogposts = blogposts, user=user)


@member_login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash("you are logged out")
    return redirect(url_for('core.index'))

myProject/member_login/templates/member_login/confirm_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p>Welcome to YPLN! Thanks for signing up. Please follow the link to activate your account</p>
    <p><a href = "{{ confirm_url }}">{{ confirm_url }}</a></p>
</body>
</html>

myProject/member_login/templates/member_login/dashboard.html
{% extends 'base_dashboard.html' %}
{% block content %}
<div class="content">
    {% for posts in blogposts.items %}
    <div class="card">
        <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
        <div class="card-body" align='center'>
          <h3><a class="card-title" href="{{url_for('blog_post_bp.blog_post',blog_post_id=posts.id)}}">{{posts.title}}</a></h3>
          <a href="{{url_for('member_login.users_posts',username=posts.author.username)}}">Written By: {{posts.author.username}}</a>
          <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
          <p>Published on: {{posts.date.strftime('%Y-%m-%d')}}</p>
          <a class="btn btn-primary" href="{{url_for('blog_post_bp.blog_post',blog_post_id=posts.id)}}">Read Post</a>
        </div>
      </div>
    {% endfor %}
    
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% for page_num in blogposts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)%}
            {% if blogposts.page == page_num %}
                <li class="page-item" disabled>
                    <a class="page-link" href="{{url_for('member_login.profile', page=page_num)}}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('member_login.profile', page=page_num)}}">{{ page_num }}</a>
                </li>
            {% endif %}
        {% endfor %}
        </ul>
        </nav>
</div>
{% endblock %}

myProject/member_login/templates/member_login/form_helpers.html
{% macro render_field(field,classes) %}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    
    {% for error in field.errors %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>  
    {% endfor %}
    
  {% endif %}
{% endmacro %}

myProject/member_login/templates/member_login/signin.html
{% from "form_helpers.html" import render_field %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V16</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{{url_for('static',filename='sign_up/images/icons/favicon.ico')}}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/vendor/bootstrap/css/bootstrap.min.css')}}">

	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">

	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">

	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/vendor/animate/animate.css')}}">
	
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/vendor/css-hamburgers/hamburgers.min.css')}}">

	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/vendor/animsition/css/animsition.min.css')}}">

	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/vendor/select2/select2.min.css')}}">
	
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/vendor/daterangepicker/daterangepicker.css')}}">

	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/css/util.css')}}">
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_up/css/main.css')}}">

</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('../static/sign_up/images/bg-01.jpg');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Account Login
				</span>
				{% if not submission %}
					<div id="error-display" class="error-message"  >
						{{ message }}
					</div>
				{% endif %}
				<form class="login100-form validate-form p-b-33 p-t-5" method="POST">
					{{ form.hidden_tag() }}
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						{{ render_field(form.useremail,class_='input100') }}
						
	
						
						<!-- <input class="input100" type="text" name="username" placeholder="User name"> -->
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>
 
					<div class="wrap-input100 validate-input" data-validate="Enter password">
						{{ render_field(form.password,class_='input100')}}
						<!-- <input class="input100" type="password" name="pass" placeholder="Password"> -->
					
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>
	
					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn" id='signin'>
							Login
						</button>
					</div>
				</form>
				
				

				
				<!-- {% if message != '' %} -->
				
				<!-- {% endif %} -->
				<!-- {% with messages = get_flashed_messages(with_categories=True) %}
					{% for message in messages %}
						{% if message == 'Something went wrong, Please check your email id or password'%}
					
				  	{% endif %}
				  {% endfor %}
				{% endwith %}</p> -->
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{{url_for('static',filename='sign_up/vendor/jquery/jquery-3.2.1.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static',filename='sign_up/vendor/animsition/js/animsition.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static',filename='sign_up/vendor/bootstrap/js/popper.js')}}"></script>
	<script src="{{url_for('static',filename='sign_up/vendor/bootstrap/js/bootstrap.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static',filename='sign_up/vendor/select2/select2.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static',filename='sign_up/vendor/daterangepicker/moment.min.js')}}"></script>
	<script src="{{url_for('static',filename='sign_up/vendor/daterangepicker/daterangepicker.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static',filename='sign_up/vendor/countdowntime/countdowntime.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='sign_up/js/main.js')}}"></script>
	

</body>
</html>

myProject/member_login/templates/member_login/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V13</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{{url_for('static',filename='sign_in/images/icons/favicon.ico')}}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/vendor/bootstrap/css/bootstrap.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/fonts/iconic/css/material-design-iconic-font.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/vendor/animate/animate.css')}}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/vendor/css-hamburgers/hamburgers.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/vendor/animsition/css/animsition.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/vendor/select2/select2.min.css')}}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/vendor/daterangepicker/daterangepicker.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/css/util.css')}}">
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='sign_in/css/main.css')}}">
<!--===============================================================================================-->
</head>
<body style="background-color: #999999;">
	
	<div class="limiter">
		<div class="container-login100">
			<div class="login100-more" style="background-image: url('../static/sign_in/images/01.jpg');"></div>

			<div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50">
				<form class="login100-form validate-form" method="POST">
					{{form.hidden_tag()}}
					<span class="login100-form-title p-b-59">
						Sign Up
					</span>

					<div class="wrap-input100 validate-input" data-validate="Name is required">
						<span class="label-input100">Full Name</span>
						{{form.fullname(class_='input100')}}
						<!-- <input class="input100" type="text" name="name" placeholder="Name..."> -->
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<span class="label-input100">Email</span>
						{{form.useremail(class_='input100')}}
						<!-- <input class="input100" type="text" name="email" placeholder="Email addess..."> -->
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Username is required">
						<span class="label-input100">Username</span>
						{{form.username(class_='input100')}}
						<!-- <input class="input100" type="text" name="username" placeholder="Username..."> -->
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						{{form.password(class_='input100')}}
						<!-- <input class="input100" type="text" name="pass" placeholder="*************"> -->
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Repeat Password is required">
						<span class="label-input100">Repeat Password</span>
						{{form.repeat_password(class_='input100')}}
						<!-- <input class="input100" type="text" name="repeat-pass" placeholder="*************"> -->
						<span class="focus-input100"></span>
					</div>

					<div class="flex-m w-full p-b-33">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								<span class="txt1">
									I agree to the
									<a href="#" class="txt2 hov1">
										Terms of User
									</a>
								</span>
							</label>
						</div>

						
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Sign Up
							</button>
						</div>

						<a href="{{url_for('member_login.sign_in')}}" class="dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30">
							Sign in
							<i class="fa fa-long-arrow-right m-l-5"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='sign_in/vendor/jquery/jquery-3.2.1.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='sign_in/vendor/animsition/js/animsition.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='sign_in/vendor/bootstrap/js/popper')}}.js"></script>
	<script src="{{url_for('static', filename='sign_in/vendor/bootstrap/js/bootstrap.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='sign_in/vendor/select2/select2.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='sign_in/vendor/daterangepicker/moment.min.js')}}"></script>
	<script src="{{url_for('static', filename='sign_in/vendor/daterangepicker/daterangepicker.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='sign_in/vendor/countdowntime/countdowntime.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static',filename='sign_in/js/main.js')}}"></script>

</body>
</html>

myProject/member_login/templates/member_login/unconfirmed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
    <p>Didn't get the email? <a href="{{url_for('member_login.resend_confirmation')}}">Resend</a>.</p>
</body>
</html>

myProject/member_login/templates/member_login/user_profile.html
{% extends 'base_dashboard.html' %}
{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit Profile</h4>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {{ form.hidden_tag() }}
                            <div class="row">
                                <div class="col-md-5 pr-1">
                                    <div class="form-group">
                                        <label>Company (disabled)</label>
                                        <input type="text" class="form-control" disabled="" placeholder="Company" value="Young Politicians and Leaders Network">
                                    </div>
                                </div>
                                <div class="col-md-3 px-1">
                                    <div class="form-group">
                                        <label>Username</label>
                                        {{ form.username(class_='form-control') }}
                                        <!-- <input type="text" class="form-control" placeholder="Username" value="michael23"> -->
                                    </div>
                                </div>
                                <div class="col-md-4 pl-1">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Email address</label>
                                        {{ form.useremail(class_='form-control') }}
                                        <!-- <input type="email" class="form-control" placeholder="Email"> -->
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 pr-1">
                                    <div class="form-group">
                                        <label>First Name</label>
                                        {{ form.first_name(class_='form-control') }}
                                        <!-- <input type="text" class="form-control" placeholder="Company" value="Mike"> -->
                                    </div>
                                </div>
                                <div class="col-md-6 pl-1">
                                    <div class="form-group">
                                        <label>Last Name</label>
                                        {{ form.last_name(class_='form-control') }}
                                        <!-- <input type="text" class="form-control" placeholder="Last Name" value="Andrew"> -->
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Address</label>
                                        {{ form.address(class_='form-control') }}
                                        <!-- <input type="text" class="form-control" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09"> -->
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pr-1">
                                    <div class="form-group">
                                        <label>City</label>
                                        {{ form.city(class_='form-control') }}
                                        <!-- <input type="text" class="form-control" placeholder="City" value="Mike"> -->
                                    </div>
                                </div>
                                <div class="col-md-4 px-1">
                                    <div class="form-group">
                                        <label>Country</label>
                                        {{ form.country(class_='form-control') }}
                                        <!-- <input type="text" class="form-control" placeholder="Country" value="Andrew"> -->
                                    </div>
                                </div>
                                <div class="col-md-4 pl-1">
                                    <div class="form-group">
                                        <label>Postal Code</label>
                                        {{ form.postal_code(class_='form-control') }}
                                        <!-- <input type="number" class="form-control" placeholder="ZIP Code"> -->
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>About Me</label>
                                        {{ form.about_me(class_='form-control') }}
                                        <!-- <textarea rows="4" cols="80" class="form-control" placeholder="Here can be your description" value="Mike">Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.</textarea> -->
                                    </div>
                                </div>
                            </div>
                            {{ form.submit(class_='btn btn-info')}}
                            <!-- <button type="submit" class="btn btn-info btn-fill pull-right">Update Profile</button> -->
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-user">
                    <div class="card-image">
                        <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400" alt="...">
                    </div>
                    <div class="card-body">
                        <div class="author">
                            <a href="#">
                                <img class="avatar border-gray" src="{{url_for('static', filename = 'dashboard/assets/img/faces/face-3.jpg')}}" alt="...">
                                <h5 class="title">Mike Andrew</h5>
                            </a>
                            <p class="description">     
                                michael24
                            </p>
                        </div>
                        <p class="description text-center">
                            "Lamborghini Mercy
                            <br> Your chick she so thirsty
                            <br> I'm in that two seat Lambo"
                        </p>
                    </div>
                    <hr>
                    <div class="button-container mr-auto ml-auto">
                        <button href="#" class="btn btn-simple btn-link btn-icon">
                            <i class="fa fa-facebook-square"></i>
                        </button>
                        <button href="#" class="btn btn-simple btn-link btn-icon">
                            <i class="fa fa-twitter"></i>
                        </button>
                        <button href="#" class="btn btn-simple btn-link btn-icon">
                            <i class="fa fa-google-plus-square"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}